# Generated by Django 3.1.2 on 2021-08-09 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('nombre_cliente', models.CharField(max_length=150, unique=True, verbose_name='Nombre cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('nombre_estado', models.CharField(max_length=150, unique=True, verbose_name='Nombre estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='FaseProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('nombre_fase', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la fase')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Correo electronico')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
            },
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('nombre_tipo', models.CharField(max_length=100, unique=True, verbose_name='Nombre tipo proyecto')),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('nombre_proyecto', models.CharField(max_length=150, unique=True, verbose_name='Nombre proyecto')),
                ('objetivo', models.TextField(verbose_name='Objetivo')),
                ('presupuesto', models.FloatField(verbose_name='Presupuesto')),
                ('presupuesto_ejecutado', models.FloatField(verbose_name='Presupuesto ejecutado')),
                ('numero_activdades', models.IntegerField(verbose_name='Número de activiades')),
                ('fecha_inicial', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_final', models.DateField(verbose_name='Fecha fin')),
                ('nombre_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cliente')),
                ('nombre_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.estado')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.responsable')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tipoproyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('nombre_actividad', models.CharField(max_length=150, unique=True, verbose_name='Nombre de actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción de la actividad')),
                ('meta', models.IntegerField(verbose_name='Meta')),
                ('avance', models.IntegerField(null=True, verbose_name='Avance')),
                ('fecha_inicial', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_final', models.DateField(verbose_name='Fecha fin')),
                ('nombre_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.estado')),
                ('nombre_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.faseproyecto')),
                ('nombre_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.proyecto')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
