# Generated by Django 3.1.2 on 2021-08-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='numero_activdades',
            field=models.IntegerField(null=True, verbose_name='Número de activiades'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto_ejecutado',
            field=models.FloatField(null=True, verbose_name='Presupuesto ejecutado'),
        ),
    ]
