# Generated by Django 3.1.2 on 2021-08-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210809_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_cliente',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='estado',
            old_name='nombre_estado',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='nombre_cliente',
            new_name='cliente',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='nombre_estado',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.estado'),
        ),
    ]
