# Generated by Django 3.1.2 on 2021-08-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210811_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='nombre_fase',
            new_name='fase',
        ),
        migrations.RenameField(
            model_name='faseproyecto',
            old_name='nombre_fase',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tipoproyecto',
            old_name='nombre_tipo',
            new_name='nombre',
        ),
    ]
