# Generated by Django 3.1.2 on 2021-08-11 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210811_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='nombre_proyecto',
            new_name='proyecto',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='nombre_proyecto',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='nombre_estado',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.estado'),
        ),
    ]
