# Generated by Django 2.2.5 on 2021-09-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210811_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='slug',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
