# Generated by Django 2.2.5 on 2021-09-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_proyecto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='nombre_actividad',
            field=models.CharField(max_length=150, verbose_name='Nombre de actividad'),
        ),
    ]
