# Generated by Django 2.2.5 on 2021-10-01 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210929_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Responsable'),
        ),
    ]
