# Generated by Django 2.2.5 on 2021-10-05 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_actividad_responsable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='nombreCliente',
        ),
    ]
