# Generated by Django 2.2.5 on 2021-11-03 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20211103_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'default_permissions': ('change', 'add', 'delete', 'view')},
        ),
    ]
