# Generated by Django 2.2.5 on 2021-11-16 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_auto_20211103_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsable',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='email',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='nombre',
        ),
        migrations.AddField(
            model_name='responsable',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
